spring.application.name=cratis-app
cratis.arc.tenancy.resolvers=header
cratis.arc.tenancy.required=true
cratis.arc.tenancy.header-name=x-cratis-tenant-id
cratis.arc.command-scope-completion-timeout=30s
cratis.chronicle.event-store=CratisApp
cratis.chronicle.default-sink-type-id=InMemory
cratis.chronicle.namespace-resolution.strategy=fixed
cratis.chronicle.namespace=Default
